stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

varibales:
  IMAGE: sumeet/django-blog:CICD  
build_job:
  stage: build
<<<<<<< HEAD
  script:
    - docker build -t django_app:latest .
=======
  script:
    - docker build -t $IMAGE .
>>>>>>> d63da51 (solved the docker-compose error)
  
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "testing ...."
  tags:
    - dev

push_job:
  stage: push_to_dockerhub
  script:
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker push $IMAGE
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker compose pull
    - docker compose up -d --force-recreate
  tags:
    - dev   

