stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

variables:
  IMAGE: sumeet02/django-blog:CICD

build_job:
  stage: build
  script:
    - docker build -t $IMAGE .
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "testing ...."
  tags:
    - dev

push_job:
  stage: push_to_dockerhub
  script:
    - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
    - docker push $IMAGE
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker compose pull
    - docker compose up -d --force-recreate
  tags:
    - dev   

