stages:
  - build
  - test
  - push_to_dockerhub
  - depploy

build_job:
  stage: build
  scripts:
    - docker build -t django_app:latest .
  
  tags:
    - dev

test_job:
  stage: test
  script:
    - echo "testing ...."

push_job:
  stage: push_to_dockerhub
  script:
    - docker login -u $DOCKERHUB_USER -P $DOCKERHUB_PASS
    - docker image tag django_app:latest $DOCKERHUB_USER/django_app:latest   
    - docker push $DOCKERHUB_USER/django_app:latest
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker-compose up -d
  tags:
    - dev   

